# coding:utf-8
from ai_data_synchronization.constants.SysConst import _constants


# 构造一个常量类的实例变量
RESPONSE_CODE_MSG_CONSTANTS = _constants()

RESPONSE_CODE_MSG_CONSTANTS.CODE_NO_INFO = "1001"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_NO_INFO = "结果为空"

# 系统异常错误码和错误信息定义
RESPONSE_CODE_MSG_CONSTANTS.CODE_SYS_ERROR = "9999"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_SYS_ERROR = "系统繁忙，请稍后再试"

RESPONSE_CODE_MSG_CONSTANTS.CODE_SHOPS_INFO_CLEAN_DATA_FAILED = '9995'
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_SHOPS_INFO_CLEAN_DATA_FAILED = '清洗数据失败'

# 数据库操作异常错误和错误信息定义
RESPONSE_CODE_MSG_CONSTANTS.CODE_DATABASE_SELECT_ERROR = "400"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_DATABASE_SELECT_ERROR = "数据库查询操作失败"

RESPONSE_CODE_MSG_CONSTANTS.CODE_DATABASE_UPDATE_ERROR = "401"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_DATABASE_UPDATE_ERROR = "数据库更新操作失败"

RESPONSE_CODE_MSG_CONSTANTS.CODE_DATABASE_DELETE_ERROR = "402"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_DATABASE_DELETE_ERROR = "数据库删除操作失败"

RESPONSE_CODE_MSG_CONSTANTS.CODE_DATABASE_INSERT_ERROR = "403"
RESPONSE_CODE_MSG_CONSTANTS.MESSAGE_DATABASE_INSERT_ERROR = "数据库插入操作失败"


